Fix path in test command in Webapp.yml

diff --git a/.github/workflows/Webapp.yml b/.github/workflows/Webapp.yml
--- a/.github/workflows/Webapp.yml
+++ b/.github/workflows/Webapp.yml
@@ -55,7 +55,7 @@ jobs:
           dotnet build "Vehiculos.WEB/Web/*.csproj" --configuration Release --no-restore
 
       - name: Run tests
-        run: dotnet test "DVehiculos.WEB/Vehiculos.WEB.sln" --no-restore --verbosity normal --configuration Release || echo "No tests found or test execution failed"
+        run: dotnet test "Vehiculos.WEB/Vehiculos.WEB.sln" --no-restore --verbosity normal --configuration Release || echo "No tests found or test execution failed"
 
       - name: dotnet publish
         run: dotnet publish "Vehiculos.WEB/Web/Web.csproj/*.csproj" -c Release -o ./publish --no-restore
